const data={
    products:[
        {
            _id:"1",
            name: "Thermaltake Mouse",
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 34,
            brand: 'Thermaltake',
            rating: 4.5,
            numReview: 15,
            description: 'high quality product',
        },
        {
            _id:"2",
            name: "HyperX Mouse",
            image: '/images/p2.jpg',
            price: 225,
            countInStock: 20,
            brand: 'Thermaltake',
            rating: 4,
            numReview: 10,
            description: 'high quality product',
        },
        {
            _id:"3",
            name: "Logitech Mouse",
            image: '/images/p3.jpg',
            price: 250,
            countInStock: 50,
            brand: 'Thermaltake',
            rating: 3.5,
            numReview: 30,
            description: 'high quality product',
        },
        {
            _id:"4",
            name: "Asus Mouse",
            image: '/images/p4.jpg',
            price: 120,
            countInStock: 103,
            brand: 'Thermaltake',
            rating: 3,
            numReview: 15,
            description: 'high quality product',
        },
        {
            _id:"5",
            name: "Logitech Mouse",
            image: '/images/p5.jpg',
            price: 100,
            countInStock: 0,
            brand: 'Thermaltake',
            rating: 5,
            numReview: 29,
            description: 'high quality product',
        },
        {
            _id:"6",
            name: "Glorious Mouse",
            image: '/images/p6.jpg',
            price: 200,
            countInStock: 5,
            brand: 'Glorious',
            rating: 5,
            numReview: 35,
            description: 'high quality product',
        },
    ]
}

export default data;